import Layout from '@/components/Layouts/Layout'
import React from 'react'

export const metadata = {
  title: "About | NextZen Software Solutions",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <Layout>
      <h1 className=" text-center text-3xl mt-20">About Page</h1>
    </Layout>
  );
}

export default page