"use client";
import Layout from "@/components/Layouts/Layout";
import LetsWorks from "@/components/LetsWorks";
import Image from "next/image";
import React, { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";

const metadata = {
  title: "About | NextZen Software Solutions",
  description: "Generated by create next app",
};

const SectionTitle = ({ title, highlight }) => (
  <h1 className="text-2xl font-bold text-center lg:text-4xl md:text-3xl">
    {title} <span className="text-purple-500">{highlight}</span>
  </h1>
);

const AboutSection = ({ title, content }) => (
  <div className="w-full px-4 lg:w-1/2">
    {content.map((text, index) => (
      <p
        key={index}
        className="mt-3 text-base text-gray-600 md:text-sm lg:text-base"
      >
        {text}
      </p>
    ))}
  </div>
);

const ImageSection = ({ src, alt }) => (
  <div className="flex justify-center lg:w-1/2">
    <Image
      src={src}
      width={300}
      height={300}
      objectFit="cover"
      alt={alt}
      className="h-auto"
    />
  </div>
);

// const TeamCard = ({ src, name, position }) => (
//   <div className="overflow-hidden bg-white rounded-md shadow-xl h-96">
//     <Image
//       src={src}
//       width={300}
//       height={300}
//       objectFit="contain"
//       alt={name}
//       className="w-full h-64"
//     />
//     <h4 className="text-center pt-2 font-bold text-[20px] mt-5">{name}</h4>
//     <p className="text-center pt-1 text-gray-600 text-[16px]">{position}</p>
//   </div>
// );

const Page = () => {
  useEffect(() => {
    AOS.init({
      duration: 1000, // Animation duration
      offset: 200, // Offset (distance from top to trigger animation)
    });
  }, []);
  return (
    <>
      <Layout>
        {/* Hero Section */}
        <div className="container">
          <div className=" h-[400px] bg-purple-600  flex flex-col justify-center items-center">
            <h1
              className="lg:text-[42px] md:text-[24px] text-[22px] font-bold font-sans text-white mt-10 aos-box "
              data-aos="fade-up"
            >
              About Us
            </h1>
            <p
              className="text-center max-w-2xl mx-auto text-white lg:text-[16px] md:text-[14px] text-sm mt-2 font-sans font-semibold lg:px-0 px-4 aos-box "
              data-aos="fade-up"
            >
              Our talented{" "}
              <a href="/" className=" hover:underline">
                NextZen
              </a>{" "}
              developer has built multiple third-party products and worked on
              numerous{" "}
              <a href="/" className=" hover:underline">
                NextZen
              </a>{" "}
              websites. NextZen knowledgeable services to assist you all with
              the style and development you would really like for the NextZen
              theme. We help you use the NextZen theme to develop unique
              solutions for various website types.
            </p>
          </div>

          {/* Vision Section */}
          <div
            className="max-w-6xl px-4 mx-auto mt-10 aos-box "
            data-aos="fade-up"
          >
            <SectionTitle title="Our" highlight="Vision" />
            <div
              className="flex flex-col gap-10 mt-10 lg:flex-row md:flex-row aos-box "
              data-aos="fade-up"
            >
              <AboutSection
                content={[
                  "Our vision is to provide web design, web development, web solutions, cost-effective and timely solutions to clients all over the world as a one-stop-shop for all web-based services.",
                  "We forever expect to add real worth to your business through our ability in recent, unforeseen and creative ways to form an online website extraordinary in quality whenever by providing the best website design with every single project so as to help achieve and surpass your business goals.",
                ]}
              />
              <ImageSection src="/images/vision1.png" alt="Vision Image" />
            </div>
          </div>

          {/* Mission Section */}
          <div
            className="max-w-6xl px-4 mx-auto mt-10 aos-box "
            data-aos="fade-up"
          >
            <SectionTitle title="Our" highlight="Mission" />
            <div className="flex flex-col items-center gap-10 mt-10 lg:flex-row">
              <ImageSection src="/images/mission.png" alt="Mission Image" />
              <ul className="max-w-lg px-4 text-gray-600 list-disc lg:pl-8">
                <li>To provide quick and efficient solutions to clients.</li>
                <li>
                  To inspire and develop systematic skills within NextZen
                  Solutions.
                </li>
                <li>
                  To train the team for global client handling and strong
                  customer relationships.
                </li>
                <li>
                  To hold regular tech-meets discussing the latest innovations
                  and implementations.
                </li>
              </ul>
            </div>
          </div>

          {/* Team Section */}
          <div
            className="max-w-6xl px-4 mx-auto mt-10 text-center aos-box "
            data-aos="fade-up"
          >
            <SectionTitle title="Our" highlight="Team" />
            <p className="text-gray-600 max-w-2xl mx-auto text-sm md:text-[16px] lg:text-[18px]">
              Our team is dedicated to innovation and excellence, providing the
              best web solutions to our global clients.
            </p>
            {/* <div className="grid gap-4 mt-10 lg:grid-cols-3">
              <TeamCard
                src="/images/majid.jpg"
                name="SHEIKH MAJID"
                position="Founder & CEO"
              />
              <TeamCard
                src="/images/hamid.jpg"
                name="ABOU HAMID"
                position="Co-Founder"
              />
              <TeamCard
                src="/images/syed.jpg"
                name="SYED F. YUSUF"
                position="Software Developer"
              />
            </div> */}
          </div>
        </div>
        <div>
          <LetsWorks />
        </div>
      </Layout>
    </>
  );
};

export default Page;
