"use client";
import Layout from "@/components/Layouts/Layout";
import Link from "next/link";
import React, { useEffect, useRef } from "react";
import emailjs from "@emailjs/browser";
import toast from "react-hot-toast";
import { useRouter } from "next/navigation";
import LetsWorks from "@/components/LetsWorks";
import AOS from "aos";
import "aos/dist/aos.css";

const metadata = {
  title: "Contact | NextZen Software Solutions",
  description: "Generated by create next app",
};

const Page = () => {
  useEffect(() => {
    AOS.init({
      duration: 1000, // Animation duration
      offset: 200, // Offset (distance from top to trigger animation)
    });
  }, []);
  const form = useRef();
  const router = useRouter();

  const sendEmail = (e) => {
    e.preventDefault();

    emailjs
      .sendForm("service_omf5qb9", "template_d7u3m5s", form.current, {
        publicKey: "Jh-lo_fp8YOBiXnZ5",
      })
      .then(
        () => {
          console.log("SUCCESS!");
          toast.success("Email Sent Successfully!");
          router.push("/subContact");
        },
        (error) => {
          console.log("FAILED...", error.text);
        }
      );
  };

  return (
    <Layout>
      <div className="container">
        <div className="relative flex flex-col items-center justify-center w-full mb-24 bg-purple-600 h-[400px]">
          <h1
            className="mb-2 font-mono text-2xl font-extrabold text-center text-white lg:text-5xl md:text-3xl mt-28 aos-box "
            data-aos="fade-up"
          >
            Contact Us.
          </h1>
          <h3
            className="px-3 mb-10 font-serif text-sm text-center text-white lg:text-xl md:text-xl lg:px-0 aos-box "
            data-aos="fade-up"
          >
            Get in touch or shoot us an email directly on{" "}
            <span className="font-semibold cursor-pointer text-gray-950">
              info@nextzen.com
            </span>
          </h3>
          {/* <div className="lg:flex  mx-auto max-w-[90%] -translate-y-10 absolute inset-0 mt-5 space-x-2 hidden ">
            <div className="w-32 h-32 bg-red-500 rounded-full"></div>
            <div className="w-32 h-32 bg-red-500 rounded-full"></div>
            <div className="w-32 h-32 bg-red-500 rounded-full"></div>
            <div className="w-32 h-32 bg-red-500 rounded-full"></div>
            <div className="w-32 h-32 bg-red-500 rounded-full"></div>
            <div className="w-32 h-32 bg-red-500 rounded-full"></div>
            <div className="w-32 h-32 bg-red-500 rounded-full"></div>
            <div className="w-32 h-32 bg-red-500 rounded-full"></div>
            <div className="w-32 h-32 bg-red-500 rounded-full"></div>
          </div> */}
        </div>
      </div>
      <div
        className="flex max-w-6xl px-3 mx-auto mb-10 bg-slate-50 lg:px-0 aos-box "
        data-aos="fade-up"
      >
        <div className="flex justify-center w-full py-12 border rounded shadow-md lg:px-0 border-slate-400">
          <form
            ref={form}
            onSubmit={sendEmail}
            className="w-full max-w-5xl px-4 mx-auto space-y-4 md:px-8"
          >
            <div className="flex flex-col space-y-4 md:flex-row md:space-y-0 md:space-x-7">
              <div className="flex flex-col w-full">
                <div className="">
                  <label
                    htmlFor="full-name"
                    className="block mb-1 font-mono text-lg font-semibold text-pure-greys-500"
                  >
                    Name
                  </label>
                  <input
                    type="text"
                    name="user_name"
                    id="full-name"
                    className="w-full px-4 py-3 text-gray-700 bg-white border rounded-md focus:outline-none focus:ring focus:ring-slate-200"
                    placeholder="Enter Your Name..."
                    required
                  />
                </div>
                <div className="mt-2">
                  <label
                    htmlFor="email"
                    className="block mb-1 font-mono text-lg font-semibold text-pure-greys-500"
                  >
                    Email
                  </label>
                  <input
                    type="email"
                    name="user_email"
                    id="email"
                    className="w-full px-4 py-3 text-gray-700 bg-white border rounded-md focus:outline-none focus:ring focus:ring-slate-200"
                    placeholder="Enter Your Email..."
                    required
                  />
                </div>
              </div>
            </div>
            <div className="mt-4">
              <label
                htmlFor="message"
                className="block mb-2 font-mono text-lg font-semibold text-pure-greys-500"
              >
                Write Message
              </label>
              <textarea
                id="message"
                name="message"
                className="w-full px-4 py-2 text-gray-700 bg-white border rounded-md focus:outline-none focus:ring focus:ring-slate-200"
                rows={4}
                placeholder="Enter Your Message..."
                required
              ></textarea>
            </div>
            <div className="flex flex-col gap-5 mt-4 md:flex-row">
              <a href="mailto:sakib@arlogiq.com" className="flex-1">
                <button
                  type="submit"
                  value="Send"
                  className="w-full px-4 py-3 font-bold text-white bg-black rounded-md hover:bg-gray-800 focus:outline-none focus:ring focus:ring-blue-200"
                >
                  Send Message
                </button>
              </a>
              <Link href="/" className="flex-1">
                <button className="w-full px-4 py-3 font-bold text-white bg-black rounded-md hover:bg-gray-800 focus:outline-none focus:ring focus:ring-blue-200">
                  Home
                </button>
              </Link>
            </div>
          </form>
        </div>
      </div>
      <div>
        <LetsWorks />
      </div>
    </Layout>
  );
};

// export const metadata = metadata;
export default Page;
