"use client";
import Layout from "@/components/Layouts/Layout";
import Link from "next/link";
import React, { useRef } from "react";
import emailjs from "@emailjs/browser";
import toast from "react-hot-toast";
import { useRouter } from "next/navigation";
import LetsWorks from "@/components/LetsWorks";

const metadata = {
  title: "Contact | NextZen Software Solutions",
  description: "Generated by create next app",
};

const Page = () => {
  const form = useRef();
  const router = useRouter();

  const sendEmail = (e) => {
    e.preventDefault();

    emailjs
      .sendForm("service_omf5qb9", "template_d7u3m5s", form.current, {
        publicKey: "Jh-lo_fp8YOBiXnZ5",
      })
      .then(
        () => {
          console.log("SUCCESS!");
          toast.success("Email Sent Successfully!");
          router.push("/subContact");
        },
        (error) => {
          console.log("FAILED...", error.text);
        }
      );
  };

  return (
    <Layout>
      <div>
        <div className="h-80 w-full bg-purple-600 flex flex-col justify-center items-center mb-24 relative">
          <h1 className="text-center text-white lg:text-5xl md:text-3xl text-2xl font-mono font-extrabold mt-28 mb-2">
            Contact Us.
          </h1>
          <h3 className="text-center lg:text-xl md:text-xl text-sm font-serif text-white mb-10 lg:px-0 px-3">
            Get in touch or shoot us an email directly on{" "}
            <span className="font-semibold text-gray-950 cursor-pointer">
              NextZenSoftware1234@gmail.com
            </span>
          </h3>
          <div className="lg:flex  mx-auto max-w-[90%] -translate-y-10 absolute inset-0 mt-5 space-x-2 hidden ">
            <div className="h-32 w-32 rounded-full bg-red-500"></div>
            <div className="h-32 w-32 rounded-full bg-red-500"></div>
            <div className="h-32 w-32 rounded-full bg-red-500"></div>
            <div className="h-32 w-32 rounded-full bg-red-500"></div>
            <div className="h-32 w-32 rounded-full bg-red-500"></div>
            <div className="h-32 w-32 rounded-full bg-red-500"></div>
            <div className="h-32 w-32 rounded-full bg-red-500"></div>
            <div className="h-32 w-32 rounded-full bg-red-500"></div>
            <div className="h-32 w-32 rounded-full bg-red-500"></div>
          </div>
        </div>
      </div>
      <div className="flex max-w-6xl mx-auto mb-10 bg-slate-50 lg:px-0 px-3">
        <div className="w-full py-12 lg:px-0 rounded shadow-md border  border-slate-400 flex justify-center">
          <form
            ref={form}
            onSubmit={sendEmail}
            className="space-y-4 max-w-5xl mx-auto w-full px-4 md:px-8"
          >
            <div className="flex flex-col md:flex-row space-y-4 md:space-y-0 md:space-x-7">
              <div className="flex flex-col w-full">
                <div className="">
                  <label
                    htmlFor="full-name"
                    className="block mb-1 text-lg font-mono font-semibold text-pure-greys-500"
                  >
                    Name
                  </label>
                  <input
                    type="text"
                    name="user_name"
                    id="full-name"
                    className="w-full px-4 py-3 text-gray-700 bg-white border rounded-md focus:outline-none focus:ring focus:ring-slate-200"
                    placeholder="Enter Your Name..."
                    required
                  />
                </div>
                <div className="mt-2">
                  <label
                    htmlFor="email"
                    className="block mb-1 text-lg font-mono font-semibold text-pure-greys-500"
                  >
                    Email
                  </label>
                  <input
                    type="email"
                    name="user_email"
                    id="email"
                    className="w-full px-4 py-3 text-gray-700 bg-white border rounded-md focus:outline-none focus:ring focus:ring-slate-200"
                    placeholder="Enter Your Email..."
                    required
                  />
                </div>
              </div>
            </div>
            <div className="mt-4">
              <label
                htmlFor="message"
                className="block mb-2 text-lg font-mono font-semibold text-pure-greys-500"
              >
                Write Message
              </label>
              <textarea
                id="message"
                name="message"
                className="w-full px-4 py-2 text-gray-700 bg-white border rounded-md focus:outline-none focus:ring focus:ring-slate-200"
                rows={4}
                placeholder="Enter Your Message..."
                required
              ></textarea>
            </div>
            <div className="flex flex-col md:flex-row gap-5 mt-4">
              <a href="mailto:sakib@arlogiq.com" className="flex-1">
                <button
                  type="submit"
                  value="Send"
                  className="w-full px-4 py-3 font-bold text-white bg-black rounded-md hover:bg-gray-800 focus:outline-none focus:ring focus:ring-blue-200"
                >
                  Send Message
                </button>
              </a>
              <Link href="/" className="flex-1">
                <button className="w-full px-4 py-3 font-bold text-white bg-black rounded-md hover:bg-gray-800 focus:outline-none focus:ring focus:ring-blue-200">
                  Home
                </button>
              </Link>
            </div>
          </form>
        </div>
      </div>
      <div>
        <LetsWorks />
      </div>
    </Layout>
  );
};

// export const metadata = metadata;
export default Page;
